var arrays = {
	"Grass": [
	 [],
	 ["BULBASAUR", "IVYSAUR", "VENUSAUR", "ODDISH", "GLOOM", "VILEPLUME", "PARAS", "PARASECT", "BELLSPROUT", "WEEPINBELL", "VICTREEBEL", "EXEGGCUTE", "EXEGGUTOR", "TANGELA"],
	 ["CHIKORITA", "BAYLEEF", "MEGANIUM", "BELLOSSOM", "HOPPIP", "SKIPLOOM", "JUMPLUFF", "SUNKERN", "SUNFLORA", "CELEBI"],
	 ["TREECKO", "GROVYLE", "SCEPTILE", "LOTAD", "LOMBRE", "LUDICOLO", "SEEDOT", "NUZLEAF", "SHIFTRY", "SHROOMISH", "BRELOOM", "ROSELIA", "CACNEA", "CACTURNE", "LILEEP", "CRADILY", "TROPIUS"],
	 ["TURTWIG", "GROTLE", "TORTERRA", "BUDEW", "ROSERADE", "WORMADAM", "CHERUBI", "CHERRIM", "CHERRIM_1", "CARNIVINE", "SNOVER", "ABOMASNOW", "TANGROWTH", "LEAFEON", "ROTOM_5", "SHAYMIN", "SHAYMIN_1"],
	 ["SNIVY", "SERVINE", "SERPERIOR", "PANSAGE", "SIMISAGE", "SEWADDLE", "SWADLOON", "LEAVANNY", "COTTONEE", "WHIMSICOTT", "PETILIL", "LILLIGANT", "MARACTUS", "DEERLING", "DEERLING_1", "DEERLING_2", "DEERLING_3", "SAWSBUCK", "SAWSBUCK_1", "SAWSBUCK_2", "SAWSBUCK_3", "FOONGUS", "AMOONGUSS", "FERROSEED", "FERROTHORN", "VIRIZION", "BLACKDOOR"],
	 ["CHESPIN", "QUILLADIN", "CHESNAUGHT", "SKIDDO", "GOGOAT", "PHANTUMP", "TREVENANT", "PUMPKABOO", "GOURGEIST", "VENUSAUR_1", "SCEPTILE_1", "ABOMASNOW_1"],
	 ["ROWLET", "DARTRIX", "DECIDUEYE", "FOMANTIS", "LURANTIS", "MORELULL", "SHIINOTIC", "BOUNSWEET", "STEENEE", "TSAREENA", "DHELMISE", "TAPUBULU", "KARTANA", "EXEGGUTOR_1"],
	 ["GROOKEY", "THWACKEY", "RILLABOOM", "RILLABOOM_1", "GOSSIFLEUR", "ELDEGOSS", "APPLIN", "FLAPPLE", "APPLETUN", "APPLETUN_1", "ZARUDE", "ZARUDE_1", "CALYREX", "VOLTORB_1", "ELECTRODE_1", "LILLIGANT_1", "DECIDUEYE_1", "VENUSAUR_2"],
	 ["SPRIGATITO", "FLORAGATO", "MEOWSCARADA", "SMOLIV", "DOLLIV", "ARBOLIVA", "BRAMBLIN", "BRAMBLEGHAST", "TOEDSCOOL", "TOEDSCRUEL", "CAPSAKID", "SCOVILLAIN", "BRUTEBONNET", "WOCHIEN", "IRONLEAVES", "DIPPLIN", "POLTCHAGEIST", "SINISTCHA", "OGERPON", "OGERPON_1", "OGERPON_2", "OGERPON_3", "HYDRAPPLE"],
	],
	"Poison": [
	 [],
	 ["WEEDLE", "KAKUNA", "BEEDRILL", "EKANS", "ARBOK", "NIDORANfE", "NIDORINA", "NIDOQUEEN", "NIDORANmA", "NIDORINO", "NIDOKING", "ZUBAT", "GOLBAT", "VENONAT", "VENOMOTH", "TENTACOOL", "TENTACRUEL", "GRIMER", "MUK", "GASTLY", "HAUNTER", "GENGAR", "KOFFING", "WEEZING"],
	 ["SPINARAK", "ARIADOS", "CROBAT", "QWILFISH"],
	 ["DUSTOX", "GULPIN", "SWALOT", "SEVIPER"],
	 ["STUNKY", "SKUNTANK", "SKORUPI", "DRAPION", "CROAGUNK", "TOXICROAK"],
	 ["VENIPEDE", "WHIRLIPEDE", "SCOLIPEDE", "TRUBBISH", "GARBODOR"],
	 ["SKRELP", "DRAGALGE", "BEEDRILL_1", "GENGAR_1"],
	 ["MAREANIE", "TOXAPEX", "SALANDIT", "SALAZZLE", "NIHILEGO", "POIPOLE", "NAGANADEL", "GRIMER_1", "MUK_1"],
	 ["TOXEL", "TOXTRICITY", "TOXTRICITY_1", "TOXTRICITY_2", "ETERNATUS", "ETERNATUS_1", "SLOWBRO_1", "SLOWKING_1", "WEEZING_1", "SNEASEL_1", "SNEASLER", "QWILFISH_1", "OVERQWIL", "GENGAR_2", "GARBODOR_1"],
	 ["SHROODLE", "GRAFAIAI", "VAROOM", "REVAVROOM", "GLIMMET", "GLIMMORA", "WOOPER_1", "CLODSIRE", "IRONMOTH", "OKIDOGI", "MUNKIDORI", "FEZANDIPITI", "PECHARUNT"],
	],
	"Fire": [
	 [],
	 ["CHARMANDER", "CHARMELEON", "CHARIZARD", "VULPIX", "NINETALES", "GROWLITHE", "ARCANINE", "PONYTA", "RAPIDASH", "MAGMAR", "FLAREON", "MOLTRES"],
	 ["CYNDAQUIL", "QUILAVA", "TYPHLOSION", "SLUGMA", "MAGCARGO", "HOUNDOUR", "HOUNDOOM", "MAGBY", "ENTEI", "HOOH"],
	 ["TORCHIC", "COMBUSKEN", "BLAZIKEN", "NUMEL", "CAMERUPT", "TORKOAL", "CASTFORM_1"],
	 ["CHIMCHAR", "MONFERNO", "INFERNAPE", "MAGMORTAR", "ROTOM_1", "HEATRAN"],
	 ["VICTINI", "TEPIG", "PIGNITE", "EMBOAR", "PANSEAR", "SIMISEAR", "DARUMAKA", "DARMANITAN", "DARMANITAN_1", "LITWICK", "LAMPENT", "CHANDELURE", "HEATMOR", "LARVESTA", "VOLCARONA", "RESHIRAM", "WHITEDOOR"],
	 ["FENNEKIN", "BRAIXEN", "DELPHOX", "FLETCHINDER", "TALONFLAME", "LITLEO", "PYROAR", "PYROAR_1", "VOLCANION", "CHARIZARD_1", "CHARIZARD_2", "HOUNDOOM_1", "BLAZIKEN_1", "CAMERUPT_1", "GROUDON_1"],
	 ["LITTEN", "TORRACAT", "INCINEROAR", "ORICORIO", "TURTONATOR", "BLACEPHALON", "MAROWAK_1"],
	 ["SCORBUNNY", "RABOOT", "CINDERACE", "CINDERACE_1", "CARKOL", "COALOSSAL", "COALOSSAL_1", "SIZZLIPEDE", "CENTISKORCH", "CENTISKORCH_1", "GROWLITHE_1", "ARCANINE_1", "TYPHLOSION_1", "DARMANITAN_3", "CHARIZARD_3"],
	 ["FUECOCO", "CROCALOR", "SKELEDIRGE", "CHARCADET", "ARMAROUGE", "CERULEDGE", "CHIYU", "TAUROS_2", "GOUGINGFIRE"],
	],
	"Flying": [
	 [],
	 ["BUTTERFREE", "PIDGEY", "PIDGEOTTO", "PIDGEOT", "SPEAROW", "FEAROW", "FARFETCHD", "DODUO", "DODRIO", "SCYTHER", "GYARADOS", "AERODACTYL", "ARTICUNO", "ZAPDOS", "DRAGONITE"],
	 ["HOOTHOOT", "NOCTOWL", "LEDYBA", "LEDIAN", "TOGETIC", "NATU", "XATU", "YANMA", "MURKROW", "GLIGAR", "DELIBIRD", "MANTINE", "SKARMORY", "LUGIA"],
	 ["BEAUTIFLY", "TAILLOW", "SWELLOW", "WINGULL", "PELIPPER", "MASQUERAIN", "NINJASK", "SWABLU", "ALTARIA", "SALAMENCE", "RAYQUAZA", "LUGIA_1"],
	 ["STARLY", "STARAVIA", "STARAPTOR", "MOTHIM", "COMBEE", "VESPIQUEN", "DRIFLOON", "DRIFBLIM", "HONCHKROW", "CHATOT", "MANTYKE", "TOGEKISS", "YANMEGA", "GLISCOR", "ROTOM_4"],
	 ["PIDOVE", "TRANQUILL", "UNFEZANT", "UNFEZANT_1", "WOOBAT", "SWOOBAT", "SIGILYPH", "ARCHEN", "ARCHEOPS", "DUCKLETT", "SWANNA", "EMOLGA", "RUFFLET", "BRAVIARY", "VULLABY", "MANDIBUZZ", "TORNADUS", "TORNADUS_1", "THUNDURUS", "THUNDURUS_1", "LANDORUS", "LANDORUS_1", "UFO"],
	 ["FLETCHLING", "VIVILLON", "HAWLUCHA", "NOIBAT", "NOIVERN", "YVELTAL", "PIDGEOT_1", "PINSIR_1", "AERODACTYL_1", "SALAMENCE_1", "RAYQUAZA_1", "VIVILLON_1", "VIVILLON_2", "VIVILLON_3", "VIVILLON_4", "VIVILLON_5", "VIVILLON_6", "VIVILLON_7", "VIVILLON_8", "VIVILLON_9", "VIVILLON_10", "VIVILLON_11", "VIVILLON_12", "VIVILLON_13", "VIVILLON_14", "VIVILLON_15", "VIVILLON_16", "VIVILLON_17", "VIVILLON_18", "VIVILLON_19"],
	 ["PIKIPEK", "TRUMBEAK", "TOUCANNON", "ORICORIO_1", "ORICORIO_2", "ORICORIO_3", "MINIOR", "MINIOR_7", "MINIOR_8", "MINIOR_9", "MINIOR_10", "MINIOR_11", "MINIOR_12", "MINIOR_13", "CELESTEELA"],
	 ["ROOKIDEE", "CORVISQUIRE", "CORVIKNIGHT", "CORVIKNIGHT_1", "CRAMORANT", "CRAMORANT_1", "CRAMORANT_2", "ENAMORUS", "ENAMORUS_1", "ARTICUNO_1", "ZAPDOS_1", "MOLTRES_1", "BRAVIARY_1", "BUTTERFREE_1"],
	 ["SQUAWKABILLY", "SQUAWKABILLY_1", "SQUAWKABILLY_2", "SQUAWKABILLY_3", "WATTREL", "KILOWATTREL", "BOMBIRDIER", "FLAMIGO", "IRONJUGULIS"],
	],
	"Dragon": [
	 [],
	 ["DRATINI", "DRAGONAIR"],
	 ["KINGDRA"],
	 ["VIBRAVA", "FLYGON", "BAGON", "SHELGON", "LATIAS", "LATIOS"],
	 ["GIBLE", "GABITE", "GARCHOMP", "DIALGA", "PALKIA", "GIRATINA", "GIRATINA_1", "DIALGA_2"],
	 ["AXEW", "FRAXURE", "HAXORUS", "DRUDDIGON", "DEINO", "ZWEILOUS", "HYDREIGON", "ZEKROM", "KYUREM", "KYUREM_1", "KYUREM_2"],
	 ["TYRUNT", "TYRANTRUM", "GOOMY", "SLIGGOO", "GOODRA", "ZYGARDE", "AMPHAROS_1", "ALTARIA_1", "LATIAS_1", "LATIOS_1", "GARCHOMP_1"],
	 ["DRAMPA", "JANGMOO", "HAKAMOO", "KOMMOO", "GUZZLORD", "NECROZMA_3", "ZYGARDE_1", "ZYGARDE_2"],
	 ["DRACOZOLT", "DRACOVISH", "DURALUDON", "DURALUDON_1", "DREEPY", "DRAKLOAK", "DRAGAPULT", "REGIDRAGO", "DIALGA_1", "PALKIA_1", "SLIGGOO_1", "GOODRA_1"],
	 ["CYCLIZAR", "TATSUGIRI", "TATSUGIRI_1", "TATSUGIRI_2", "FRIGIBAX", "ARCTIBAX", "BAXCALIBUR", "ROARINGMOON", "KORAIDON", "MIRAIDON", "WALKINGWAKE", "ARCHALUDON", "RAGINGBOLT"],
	],
	"Water": [
	 [],
	 ["SQUIRTLE", "WARTORTLE", "BLASTOISE", "PSYDUCK", "GOLDUCK", "POLIWAG", "POLIWHIRL", "POLIWRATH", "SLOWPOKE", "SLOWBRO", "SEEL", "DEWGONG", "SHELLDER", "CLOYSTER", "KRABBY", "KINGLER", "HORSEA", "SEADRA", "GOLDEEN", "SEAKING", "STARYU", "STARMIE", "MAGIKARP", "LAPRAS", "VAPOREON", "OMANYTE", "OMASTAR", "KABUTO", "KABUTOPS"],
	 ["TOTODILE", "CROCONAW", "FERALIGATR", "CHINCHOU", "LANTURN", "MARILL", "AZUMARILL", "POLITOED", "WOOPER", "QUAGSIRE", "SLOWKING", "CORSOLA", "REMORAID", "OCTILLERY", "SUICUNE"],
	 ["MUDKIP", "MARSHTOMP", "SWAMPERT", "SURSKIT", "CARVANHA", "SHARPEDO", "WAILMER", "WAILORD", "BARBOACH", "WHISCASH", "CORPHISH", "CRAWDAUNT", "FEEBAS", "MILOTIC", "CASTFORM_2", "SPHEAL", "SEALEO", "WALREIN", "CLAMPERL", "HUNTAIL", "GOREBYSS", "RELICANTH", "LUVDISC", "KYOGRE"],
	 ["PIPLUP", "PRINPLUP", "EMPOLEON", "BIBAREL", "BUIZEL", "FLOATZEL", "SHELLOS", "SHELLOS_1", "GASTRODON", "GASTRODON_1", "FINNEON", "LUMINEON", "ROTOM_2", "PHIONE", "MANAPHY"],
	 ["OSHAWOTT", "DEWOTT", "SAMUROTT", "PANPOUR", "SIMIPOUR", "TYMPOLE", "PALPITOAD", "SEISMITOAD", "BASCULIN", "BASCULIN_1", "TIRTOUGA", "CARRACOSTA", "FRILLISH", "FRILLISH_1", "JELLICENT", "JELLICENT_1", "ALOMOMOLA", "KELDEO", "KELDEO_1"],
	 ["FROAKIE", "FROGADIER", "GRENINJA", "BINACLE", "BARBARACLE", "CLAUNCHER", "CLAWITZER", "BLASTOISE_1", "SLOWBRO_2", "GYARADOS_1", "SWAMPERT_1", "SHARPEDO_1", "KYOGRE_1"],
	 ["POPPLIO", "BRIONNE", "PRIMARINA", "WISHIWASHI", "WISHIWASHI_1", "DEWPIDER", "ARAQUANID", "WIMPOD", "GOLISOPOD", "PYUKUMUKU", "BRUXISH", "TAPUFINI", "GRENINJA_2"],
	 ["SOBBLE", "DRIZZILE", "INTELEON", "INTELEON_1", "CHEWTLE", "DREDNAW", "DREDNAW_1", "ARROKUDA", "BARRASKEWDA", "ARCTOVISH", "URSHIFU_1", "URSHIFU_3", "BASCULIN_2", "BASCULEGION", "BASCULEGION_1", "SAMUROTT_1", "BLASTOISE_2", "KINGLER_1", "LAPRAS_1"],
	 ["QUAXLY", "QUAXWELL", "QUAQUAVAL", "WIGLETT", "WUGTRIO", "FINIZEN", "PALAFIN", "PALAFIN_1", "VELUZA", "DONDOZO", "IRONBUNDLE", "TAUROS_3"],
	],
	"Bug": [
	 [],
	 ["CATERPIE", "METAPOD", "PINSIR"],
	 ["PINECO", "FORRETRESS", "SCIZOR", "SHUCKLE", "HERACROSS"],
	 ["WURMPLE", "SILCOON", "CASCOON", "NINCADA", "SHEDINJA", "VOLBEAT", "ILLUMISE", "ANORITH", "ARMALDO"],
	 ["KRICKETOT", "KRICKETUNE", "BURMY", "BURMY_1", "BURMY_2", "WORMADAM_1", "WORMADAM_2"],
	 ["DWEBBLE", "CRUSTLE", "KARRABLAST", "ESCAVALIER", "JOLTIK", "GALVANTULA", "SHELMET", "ACCELGOR", "DURANT", "GENESECT"],
	 ["SCATTERBUG", "SPEWPA", "SCIZOR_1", "HERACROSS_1"],
	 ["GRUBBIN", "CHARJABUG", "VIKAVOLT", "CUTIEFLY", "RIBOMBEE", "BUZZWOLE", "PHEROMOSA"],
	 ["BLIPBUG", "DOTTLER", "ORBEETLE", "ORBEETLE_1", "SNOM", "FROSMOTH", "KLEAVOR"],
	 ["TAROUNTULA", "SPIDOPS", "NYMBLE", "LOKIX", "RELLOR", "RABSCA", "SLITHERWING"],
	],
	"Normal": [
	 [],
	 ["RATTATA", "RATICATE", "JIGGLYPUFF", "WIGGLYTUFF", "MEOWTH", "PERSIAN", "LICKITUNG", "CHANSEY", "KANGASKHAN", "TAUROS", "DITTO", "EEVEE", "PORYGON", "SNORLAX"],
	 ["SENTRET", "FURRET", "IGGLYBUFF", "AIPOM", "GIRAFARIG", "DUNSPARCE", "TEDDIURSA", "URSARING", "PORYGON2", "STANTLER", "SMEARGLE", "MILTANK", "BLISSEY"],
	 ["ZIGZAGOON", "LINOONE", "SLAKOTH", "VIGOROTH", "SLAKING", "WHISMUR", "LOUDRED", "EXPLOUD", "AZURILL", "SKITTY", "DELCATTY", "SPINDA", "ZANGOOSE", "CASTFORM", "KECLEON", "KECLEON_1"],
	 ["BIDOOF", "AMBIPOM", "BUNEARY", "LOPUNNY", "GLAMEOW", "PURUGLY", "HAPPINY", "MUNCHLAX", "LICKILICKY", "PORYGONZ", "REGIGIGAS", "ARCEUS"],
	 ["PATRAT", "WATCHOG", "LILLIPUP", "HERDIER", "STOUTLAND", "AUDINO", "MINCCINO", "CINCCINO", "BOUFFALANT", "MELOETTA", "MELOETTA_1", "MONICA", "HUMANOID", "F00", "F00_1"],
	 ["BUNNELBY", "DIGGERSBY", "FURFROU", "HELIOPTILE", "HELIOLISK", "KANGASKHAN_1", "LOPUNNY_1", "AUDINO_1", "FURFROU_1", "FURFROU_2", "FURFROU_3", "FURFROU_4", "FURFROU_5", "FURFROU_6", "FURFROU_7", "FURFROU_8", "FURFROU_9"],
	 ["YUNGOOS", "GUMSHOOS", "STUFFUL", "BEWEAR", "ORANGURU", "TYPENULL", "SILVALLY", "KOMALA", "RATTATA_1", "RATICATE_1"],
	 ["SKWOVET", "GREEDENT", "WOOLOO", "DUBWOOL", "ZIGZAGOON_1", "LINOONE_1", "OBSTAGOON", "INDEEDEE", "INDEEDEE_1", "WYRDEER", "URSALUNA", "ZORUA_1", "ZOROARK_1", "MEOWTH_3", "EEVEE_1", "SNORLAX_1"],
	 ["LECHONK", "OINKOLOGNE", "OINKOLOGNE_1", "TANDEMAUS", "MAUSHOLD", "MAUSHOLD_1", "FARIGIRAF", "DUDUNSPARCE", "DUDUNSPARCE_1", "URSALUNA_1", "TERAPAGOS", "TERAPAGOS_1", "TERAPAGOS_2"],
	],
	"Dark": [
	 [],
	 ["MISSINGNO", "MISSINGNO_1", "MISSINGNO_2", "MISSINGNO_3", "MISSINGNO_4", "SUBSTITUTE"],
	 ["UMBREON", "SNEASEL", "TYRANITAR"],
	 ["POOCHYENA", "MIGHTYENA", "SABLEYE", "ABSOL"],
	 ["SPIRITOMB", "WEAVILE", "DARKRAI"],
	 ["PURRLOIN", "LIEPARD", "SANDILE", "KROKOROK", "KROOKODILE", "SCRAGGY", "SCRAFTY", "ZORUA", "ZOROARK", "PAWNIARD", "BISHARP", "BRYCENMAN", "MONSTER", "MAJIN"],
	 ["PANGORO", "INKAY", "MALAMAR", "HOOPA_1", "TYRANITAR_1", "SABLEYE_1", "ABSOL_1"],
	 ["MEOWTH_1", "PERSIAN_1"],
	 ["NICKIT", "THIEVUL", "IMPIDIMP", "MORGREM", "GRIMMSNARL", "GRIMMSNARL_1", "MORPEKO", "MORPEKO_1", "URSHIFU", "URSHIFU_2"],
	 ["MASCHIFF", "MABOSSTIFF", "KINGAMBIT", "CHIENPAO", "TINGLU"],
	],
	"Electric": [
	 [],
	 ["PIKACHU", "RAICHU", "MAGNEMITE", "MAGNETON", "VOLTORB", "ELECTRODE", "ELECTABUZZ", "JOLTEON"],
	 ["PICHU", "MAREEP", "FLAAFFY", "AMPHAROS", "ELEKID", "RAIKOU"],
	 ["ELECTRIKE", "MANECTRIC", "PLUSLE", "MINUN"],
	 ["SHINX", "LUXIO", "LUXRAY", "PACHIRISU", "MAGNEZONE", "ELECTIVIRE", "ROTOM", "ROTOM_3", "PICHU_1", "PICHU_2"],
	 ["BLITZLE", "ZEBSTRIKA", "TYNAMO", "EELEKTRIK", "EELEKTROSS", "STUNFISK", "MT2"],
	 ["DEDENNE", "MANECTRIC_1", "PIKACHU_2", "PIKACHU_3", "PIKACHU_4", "PIKACHU_5", "PIKACHU_6", "PIKACHU_7"],
	 ["TOGEDEMARU", "TAPUKOKO", "XURKITREE", "ZERAORA", "RAICHU_1", "GEODUDE_1", "GRAVELER_1", "GOLEM_1", "PIKACHU_8", "PIKACHU_9", "PIKACHU_10", "PIKACHU_11", "PIKACHU_12", "PIKACHU_13", "PIKACHU_14"],
	 ["YAMPER", "BOLTUND", "PINCURCHIN", "ARCTOZOLT", "REGIELEKI", "PIKACHU_70", "PIKACHU_15"],
	 ["PAWMI", "PAWMO", "PAWMOT", "TADBULB", "BELLIBOLT", "SANDYSHOCKS", "IRONHANDS", "IRONTHORNS"],
	],
	"Psychic": [
	 [],
	 ["ABRA", "KADABRA", "ALAKAZAM", "DROWZEE", "HYPNO", "MRMIME", "JYNX", "MEWTWO", "MEW"],
	 ["ESPEON", "WOBBUFFET", "SMOOCHUM", "UNOWN", "UNOWN_1", "UNOWN_2", "UNOWN_3", "UNOWN_4", "UNOWN_5", "UNOWN_6", "UNOWN_7", "UNOWN_8", "UNOWN_9", "UNOWN_10", "UNOWN_11", "UNOWN_12", "UNOWN_13", "UNOWN_14", "UNOWN_15", "UNOWN_16", "UNOWN_17", "UNOWN_18", "UNOWN_19", "UNOWN_20", "UNOWN_21", "UNOWN_22", "UNOWN_23", "UNOWN_24", "UNOWN_25"],
	 ["RALTS", "KIRLIA", "GARDEVOIR", "MEDITITE", "MEDICHAM", "SPOINK", "GRUMPIG", "LUNATONE", "SOLROCK", "BALTOY", "CLAYDOL", "CHIMECHO", "WYNAUT", "BELDUM", "METANG", "METAGROSS", "JIRACHI", "DEOXYS", "DEOXYS_1", "DEOXYS_2", "DEOXYS_3", "UNOWN_26", "UNOWN_27"],
	 ["CHINGLING", "BRONZOR", "BRONZONG", "MIMEJR", "GALLADE", "UXIE", "MESPRIT", "AZELF", "CRESSELIA"],
	 ["MUNNA", "MUSHARNA", "GOTHITA", "GOTHORITA", "GOTHITELLE", "SOLOSIS", "DUOSION", "REUNICLUS", "ELGYEM", "BEHEEYEM"],
	 ["ESPURR", "MEOWSTIC", "MEOWSTIC_1", "HOOPA", "ALAKAZAM_1", "MEWTWO_1", "MEWTWO_2", "GARDEVOIR_1", "MEDICHAM_1", "METAGROSS_1", "GALLADE_1", "MEWTWO_3"],
	 ["TAPULELE", "COSMOG", "COSMOEM", "SOLGALEO", "LUNALA", "NECROZMA", "NECROZMA_1", "NECROZMA_2"],
	 ["HATENNA", "HATTREM", "HATTERENE", "HATTERENE_1", "MRMIME_1", "MRRIME", "CALYREX_1", "CALYREX_2", "PONYTA_1", "RAPIDASH_1", "SLOWPOKE_1"],
	 ["FLITTLE", "ESPATHRA", "SCREAMTAIL", "IRONBOULDER", "IRONCROWN"],
	],
	"Ground": [
	 [],
	 ["SANDSHREW", "SANDSLASH", "DIGLETT", "DUGTRIO", "GEODUDE", "GRAVELER", "GOLEM", "ONIX", "CUBONE", "MAROWAK", "RHYHORN", "RHYDON"],
	 ["STEELIX", "SWINUB", "PILOSWINE", "PHANPY", "DONPHAN", "LARVITAR", "PUPITAR"],
	 ["TRAPINCH", "GROUDON"],
	 ["HIPPOPOTAS", "HIPPOPOTAS_2", "HIPPOWDON", "HIPPOWDON_2", "RHYPERIOR", "MAMOSWINE"],
	 ["DRILBUR", "EXCADRILL", "GOLETT", "GOLURK"],
	 ["STEELIX_1"],
	 ["MUDBRAY", "MUDSDALE", "SANDYGAST", "PALOSSAND", "DIGLETT_1", "DUGTRIO_1"],
	 ["SILICOBRA", "SANDACONDA", "SANDACONDA_1", "STUNFISK_1", "YAMASK_1", "RUNERIGUS"],
	 ["GREATTUSK", "IRONTREADS"],
	],
	"Ice": [
	 [],
	 [],
	 [],
	 ["CASTFORM_3", "SNORUNT", "GLALIE", "REGICE"],
	 ["GLACEON", "FROSLASS"],
	 ["VANILLITE", "VANILLISH", "VANILLUXE", "CUBCHOO", "BEARTIC", "CRYOGONAL"],
	 ["AMAURA", "AURORUS", "BERGMITE", "AVALUGG", "GLALIE_1"],
	 ["CRABOMINABLE", "SANDSHREW_1", "SANDSLASH_1", "VULPIX_1", "NINETALES_1"],
	 ["EISCUE", "EISCUE_1", "GLASTRIER", "DARUMAKA_2", "DARMANITAN_2", "AVALUGG_1"],
	 ["CETODDLE", "CETITAN"],
	],
	"Steel": [
	 [],
	 [],
	 [],
	 ["MAWILE", "ARON", "LAIRON", "AGGRON", "REGISTEEL"],
	 ["SHIELDON", "BASTIODON", "LUCARIO", "PROBOPASS"],
	 ["KLINK", "KLANG", "KLINKLANG", "COBALION", "MT", "TRANSPORT"],
	 ["HONEDGE", "DOUBLADE", "AEGISLASH", "AEGISLASH_1", "KLEFKI", "MAWILE_1", "AGGRON_1", "LUCARIO_1"],
	 ["MAGEARNA", "MAGEARNA_1", "STAKATAKA", "MELTAN", "MELMETAL"],
	 ["MEOWTH_2", "PERRSERKER", "CUFANT", "COPPERAJAH", "COPPERAJAH_1", "ZACIAN_1", "ZACIAN_2", "ZAMAZENTA_1", "ZAMAZENTA_2", "MELMETAL_1"],
	 ["TINKATINK", "TINKATUFF", "TINKATON", "ORTHWORM", "GHOLDENGO"],
	],
	"Fairy": [
	 [],
	 ["CLEFAIRY", "CLEFABLE"],
	 ["CLEFFA", "TOGEPI", "SNUBBULL", "GRANBULL"],
	 [],
	 [],
	 [],
	 ["FLABEBE", "FLABEBE_1", "FLABEBE_2", "FLABEBE_3", "FLABEBE_4", "FLOETTE", "FLOETTE_1", "FLOETTE_2", "FLOETTE_3", "FLOETTE_4", "FLOETTE_5", "FLORGES", "FLORGES_1", "FLORGES_2", "FLORGES_3", "FLORGES_4", "SPRITZEE", "AROMATISSE", "SWIRLIX", "SLURPUFF", "SYLVEON", "CARBINK", "XERNEAS", "XERNEAS_1", "DIANCIE", "DIANCIE_1"],
	 ["COMFEY", "MIMIKYU", "MIMIKYU_1"],
	 ["MILCERY", "ALCREMIE", "ALCREMIE_70", "ZACIAN"],
	 ["FIDOUGH", "DACHSBUN", "FLUTTERMANE", "IRONVALIANT"],
	],
	"Fighting": [
	 [],
	 ["MANKEY", "PRIMEAPE", "MACHOP", "MACHOKE", "MACHAMP", "HITMONLEE", "HITMONCHAN"],
	 ["TYROGUE", "HITMONTOP"],
	 ["MAKUHITA", "HARIYAMA"],
	 ["RIOLU"],
	 ["TIMBURR", "GURDURR", "CONKELDURR", "THROH", "SAWK", "MIENFOO", "MIENSHAO", "TERRAKION", "BLACKBELT"],
	 ["PANCHAM"],
	 ["CRABRAWLER", "PASSIMIAN", "MARSHADOW", "MARSHADOW_1"],
	 ["CLOBBOPUS", "GRAPPLOCT", "FARFETCHD_1", "SIRFETCHD", "FALINKS", "ZAMAZENTA", "KUBFU", "MACHAMP_1"],
	 ["ANNIHILAPE", "TAUROS_1"],
	],
	"Rock": [
	 [],
	 [],
	 ["SUDOWOODO"],
	 ["NOSEPASS", "REGIROCK"],
	 ["CRANIDOS", "RAMPARDOS", "BONSLY"],
	 ["ROGGENROLA", "BOLDORE", "GIGALITH"],
	 [],
	 ["ROCKRUFF", "LYCANROC", "LYCANROC_1", "LYCANROC_2"],
	 ["ROLYCOLY", "STONJOURNER"],
	 ["NACLI", "NACLSTACK", "GARGANACL", "KLAWF"],
	],
	"Ghost": [
	 [],
	 [],
	 ["MISDREAVUS"],
	 ["SHUPPET", "BANETTE", "DUSKULL", "DUSCLOPS"],
	 ["MISMAGIUS", "DUSKNOIR"],
	 ["YAMASK", "COFAGRIGUS"],
	 ["BANETTE_1"],
	 [],
	 ["SINISTEA", "POLTEAGEIST", "CORSOLA_1", "CURSOLA", "SPECTRIER"],
	 ["GREAVARD", "HOUNDSTONE", "GIMMIGHOUL", "GIMMIGHOUL_1"],
	],
	"Bird": [
	 ["P", "I", "D", "G", "E", "Y"],
	 ["S", "P", "E", "A", "R", "O", "W"],
	 ["H", "O", "O", "T", "H", "O", "O", "T"],
	 ["T", "A", "I", "L", "L", "O", "W"],
	 ["W", "I", "N", "G", "U", "L", "L"],
	 ["S", "T", "A", "R", "L", "Y"],
	 ["P", "I", "D", "O", "V", "E"],
	 ["F", "L", "E", "T", "C", "H", "L", "I", "N", "G"],
	 ["P", "I", "K", "I", "P", "E", "K"],
	 ["R", "O", "O", "K", "I", "D", "E", "E"],
	 ["S", "Q", "U", "A", "W", "K", "A", "B", "I", "L", "L", "Y"],
	 ["W", "A", "T", "T", "R", "E", "L"],
	],
	"Critter": [
	 [],
	 [],
	 ["Z", "Z"],
	 [],
	 [],
	 [],
	 [],
	 ["_", "1"],
	 [],
	 ["Z", "Z", "_", "1"],
	 [],
	],
	"RegionalBug": [
	 [],
	 [],
	 [],
	 [],
	 ["M"],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 ["M"],
	],
	"Pseudo": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 ["X"],
	 [],
	 [],
	 [],
	 [],
	],
	"Pikaclone": [
	 [],
	 [],
	 ["2"],
	 [],
	 [],
	 [],
	 ["7", "0"],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 ["2"],
	 ["3"],
	 ["4"],
	 ["5"],
	 ["6"],
	 ["7"],
	 ["8"],
	 ["9"],
	 ["0"],
	 [],
	 ["2"],
	 ["3"],
	 ["4"],
	 ["5"],
	],
	"Eevee": [
	 [],
	 [],
	 ["J"],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Fossil": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Regional": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"GMax": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Box": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Mythical": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Ultra": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Paradox": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Starter": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Legendary": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Gimmick": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Baby": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"NewEvolution": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Spinda": [
	 [],
	],
	"Vivillon": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Alcremie": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"alc0": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"alc7": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"alc14": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"alc21": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"alc28": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"alc35": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"alc42": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"alc49": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"alc56": [
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	],
	"Types": [
	 ["o", "r", "m", "a", "l"],
	 ["i", "r", "e"],
	 ["a", "t", "e", "r"],
	 ["r", "a", "s", "s"],
	 ["l", "e", "c", "t", "r", "i", "c"],
	 ["c", "e"],
	 ["i", "g", "h", "t", "i", "n", "g"],
	 ["o", "i", "s", "o", "n"],
	 ["r", "o", "u", "n", "d"],
	 ["l", "y", "i", "n", "g"],
	 ["s", "y", "c", "h", "i", "c"],
	 ["u", "g"],
	 ["o", "c", "k"],
	 ["h", "o", "s", "t"],
	 ["r", "a", "g", "o", "n"],
	 ["a", "r", "k"],
	 ["t", "e", "e", "l"],
	 ["a", "i", "r", "y"],
	],
	"PokeBall": [
	 [],
	 [],
	 [],
	 [],
	 ["f"],
	 [],
	 ["v"],
	 [],
	 ["v"],
	 ["v"],
	 [],
	 [],
	 ["p"],
	 [],
	 ["v"],
	 [],
	 ["p"],
	 [],
	 ["x"],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 [],
	 ["v"],
	 [],
	 [],
	 [],
	],
   };